name: Update Datawrapper Chart

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-chart:
    runs-on: ubuntu-latest
    env:
      CSV_FILE: "data/hundebiss-statistik-2024.csv"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 👇 Debug-Schritt: Zeige alle Dateien an
      - name:  Liste alle Dateien auf
        run: |
          echo "Aktuelles Verzeichnis:"
          pwd
          echo "Alle Dateien:"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch data from Berlin.de
        env:
          OUTPUT_FILE: ${{ env.CSV_FILE }}
        run: python fetch-data.py

      - name: Upload to Datawrapper
        env:
          DATAWRAPPER_API_KEY: ${{ secrets.DATAWRAPPER_API_KEY }}
          CSV_FILE: ${{ env.CSV_FILE }}
        run: python create-datawrapper-chart.py