name: Update Datawrapper Chart

# Variable für den CSV-Dateinamen
env:
  CSV_FILE: "data/hundebiss-statistik-2024.csv"  # Hier kannst du den Pfad ändern

on:
  push:
  workflow_dispatch:  # Manuelles Auslösen für Tests
  schedule:
    - cron: '0 0 1 * *'  # Täglich um Mitternacht ausführen (optional)

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Daten  herunterladen (fetch-data.py)
      - name: Fetch data
        env:
          OUTPUT_FILE: ${{ env.CSV_FILE }}
        run: |
          python fetch-data.py

      # Daten zu Datawrapper hochladen (create_datawrapper_chart.py)
      - name: Upload to Datawrapper
        env:
          DATAWRAPPER_API_KEY: ${{ secrets.DATAWRAPPER_API_KEY }}
          CSV_FILE: ${{ env.CSV_FILE }}
        run: |
          python create_datawrapper_chart.py
